## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Souillac,MU,-20.5167,57.5167,73.36,67,80,20.67,broken clouds,2021-07-30 05:07:50
1,1,Zhangjiakou,CN,40.8100,114.8794,87.03,41,99,3.62,overcast clouds,2021-07-30 05:04:54
2,2,Ribeira Grande,PT,38.5167,-28.7000,70.14,87,10,6.76,clear sky,2021-07-30 05:07:50
3,3,Tokonou,GN,9.6500,-9.7833,64.81,92,85,3.78,overcast clouds,2021-07-30 05:07:51
4,4,Cabo San Lucas,MX,22.8909,-109.9124,85.60,78,2,4.00,clear sky,2021-07-30 05:07:03

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

What is the minimum temperature you would like for your trip? 65
What is the maximum temperature you would like for your trip? 72

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,Ribeira Grande,PT,38.5167,-28.7000,70.14,87,10,6.76,clear sky,2021-07-30 05:07:50
6,6,Vila Franca Do Campo,PT,37.7167,-25.4333,70.21,93,45,6.13,scattered clouds,2021-07-30 05:07:51
9,9,Ponta Do Sol,PT,32.6667,-17.1000,70.43,79,11,6.06,few clouds,2021-07-30 05:07:52
10,10,Puerto Ayora,EC,-0.7393,-90.3518,70.43,91,16,5.79,few clouds,2021-07-30 05:07:52
11,11,Broken Hill,AU,-31.9500,141.4333,66.13,33,93,20.96,overcast clouds,2021-07-30 05:07:53
13,13,Bethel,US,41.3712,-73.4140,71.04,92,75,4.61,mist,2021-07-30 05:07:53
23,23,Rikitea,PF,-23.1203,-134.9692,71.51,75,1,6.40,clear sky,2021-07-30 05:07:56
24,24,Cubuk,TR,40.2386,33.0322,68.77,51,0,4.61,clear sky,2021-07-30 05:07:56
29,29,Tambura,SS,5.6000,27.4667,68.43,92,99,2.28,overcast clouds,2021-07-30 05:07:57
34,34,Albany,US,42.6001,-73.9662,67.37,95,89,6.24,overcast clouds,2021-07-30 05:07:51

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()

City_ID                115
City                   115
Country                114
Lat                    115
Lng                    115
Max Temp               115
Humidity               115
Cloudiness             115
Wind Speed             115
Current Description    115
Date                   115
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,Ribeira Grande,PT,38.5167,-28.7000,70.14,87,10,6.76,clear sky,2021-07-30 05:07:50
6,6,Vila Franca Do Campo,PT,37.7167,-25.4333,70.21,93,45,6.13,scattered clouds,2021-07-30 05:07:51
9,9,Ponta Do Sol,PT,32.6667,-17.1000,70.43,79,11,6.06,few clouds,2021-07-30 05:07:52
10,10,Puerto Ayora,EC,-0.7393,-90.3518,70.43,91,16,5.79,few clouds,2021-07-30 05:07:52
11,11,Broken Hill,AU,-31.9500,141.4333,66.13,33,93,20.96,overcast clouds,2021-07-30 05:07:53
...,...,...,...,...,...,...,...,...,...,...,...
670,670,Arrifes,PT,37.7667,-25.7000,68.25,88,40,8.05,scattered clouds,2021-07-30 05:10:48
676,676,Kuytun,RU,54.3419,101.5036,66.25,51,100,8.52,overcast clouds,2021-07-30 05:10:50
681,681,Pacific Grove,US,36.6177,-121.9166,66.81,91,90,1.99,overcast clouds,2021-07-30 05:10:51
686,686,Bitkine,TD,11.9801,18.2138,70.63,94,100,3.22,light rain,2021-07-30 05:10:53
691,691,Hakkari,TR,37.5833,44.1667,65.98,59,40,6.91,scattered clouds,2021-07-30 05:10:54

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Ribeira Grande,PT,70.14,clear sky,38.5167,-28.7000,
6,Vila Franca Do Campo,PT,70.21,scattered clouds,37.7167,-25.4333,
9,Ponta Do Sol,PT,70.43,few clouds,32.6667,-17.1000,
10,Puerto Ayora,EC,70.43,few clouds,-0.7393,-90.3518,
11,Broken Hill,AU,66.13,overcast clouds,-31.9500,141.4333,
13,Bethel,US,71.04,mist,41.3712,-73.4140,
23,Rikitea,PF,71.51,clear sky,-23.1203,-134.9692,
24,Cubuk,TR,68.77,clear sky,40.2386,33.0322,
29,Tambura,SS,68.43,overcast clouds,5.6000,27.4667,
34,Albany,US,67.37,overcast clouds,42.6001,-73.9662,

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [15]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Ribeira Grande,PT,70.14,clear sky,38.5167,-28.7000,
6,Vila Franca Do Campo,PT,70.21,scattered clouds,37.7167,-25.4333,
9,Ponta Do Sol,PT,70.43,few clouds,32.6667,-17.1000,
10,Puerto Ayora,EC,70.43,few clouds,-0.7393,-90.3518,
11,Broken Hill,AU,66.13,overcast clouds,-31.9500,141.4333,

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [20]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))